Algoritmo "ex8_distancia"

Var
dis1, dis2, dis3, dis4, dis5, dis6, dis7:real


Inicio
Escreva ("Escreva a distância: ")
leia (dis1)

dis2 <- dis1 / 1000
dis3 <- dis1 / 100
dis4 <- dis1 / 10
dis5 <- dis1 * 10
dis6 <- dis1 * 100
dis7 <- dis1 * 1000

escreval ("A distância em quilometros de" ,dis1, " é " ,dis2, ", em hectômetros é" ,dis3, ", Em decâmetros é" ,dis4, ", Em decímetros é" ,dis5, ", Em centímetros é" ,dis6, " E em milímetros é" ,dis7)


Fimalgoritmo